sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gXxUDpDFPHkKbtwLqlwTOwtK1siVcwRxvjDnuFyiAPtgRYvCF9fEKgIVqWW4/grkO4pOBZfVY1gvmDomm3KMPO4JwTXK8xufoXhij2s+LEXVYxqRWP30OJuPLvPdHAUMFgS/OU6DzQWFQtuo8stqm3b3PfYfhABb8wwPBsoyp3jUYYpDN2XttmUElPH4GG12POOwOFQGxdiZjyn//jd7AK1VdeJFMDtN5B0UxdcgzEb2z3P+2Qy/Qjym+eaAaVDTzaD0HTSdyrm1/ItIUKvlPvej5otZNeY0J2Cod+1b/NdmZtk9Tg8NswQEwwqJBL5jvLFq4aIibwZfjYJBCXDU8UEYcjnDvQYz6Pq3nRr/Iw3aOzGYUMoC9ATPTIJBTSX36+sYGo2inIVAzu86j2B1RUz6YkXea1kuoCxnUAz6VabQiIRc1wuZMnOkT0nw29aA30F8wVmo+xowyd81bG1QB05Rf7XyDFzBumVb7IJjhHtqDA+qGn9NUV9N0Lx1/fFwS6BW5nId6ZStWjH3Oovq4cv+muA9qMO9ygtpdp9eEqqrPnYSPeLKnzbdbqR8OCxzUdfUP9i5fbgPytGez22i/skYBP2lCvGNEHqyVdS0YTA3sFUZcYSbHhSirhwh0QXpViHUbcPnpY9FebYY1/W8Oz0f49AJiSQYHYpJIGnSECM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Satyricon---Volume-03--Encolpius-and-His-Companions_5220
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy